# Generated by Django 3.2.9 on 2021-12-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(default='active', max_length=7),
        ),
    ]
