# Generated by Django 3.2.9 on 2021-12-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_owner_listing_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
