# Generated by Django 3.2.9 on 2021-12-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_winners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winners',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='winners',
            old_name='user_id',
            new_name='user',
        ),
    ]
